//
//  MakeOrderWorker.swift
//  BxTrader
//
//  Created by Issarapong Poesua on 9/22/2560 BE.
//  Copyright (c) 2560 Issarapong Poesua. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

class MakeOrderWorker {
    private var disposeBag = DisposeBag()
    
    func fetchTickers(completion: @escaping ([Ticker]) -> ()) {
        APIManager
            .sharedInstance
            .publicAPI
            .remoteTicker
            .getTickers()
            .subscribe(onNext: { completion($0) }).addDisposableTo(disposeBag)
    }
}
