//
//  MakeOrderModels.swift
//  BxTrader
//
//  Created by Issarapong Poesua on 9/22/2560 BE.
//  Copyright (c) 2560 Issarapong Poesua. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct MakeOrder {
    // MARK: Use cases
    struct RequestTicker   {
        struct Request {
            
        }
        
        struct Response {
            let tickersList: [Ticker]
        }
        
        struct ViewModel {
            struct TickerList {
                let primary: String
                let secondary: String
                let price: Double
            }
            let displayTickers: [TickerList]
        }
    }
    
    
    
}
